# Generated by Django 3.2.2 on 2021-05-10 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hero_weakness'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='backstory',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
